# livekit.yaml
port: 7880
bind_addresses:
  - ""

# ✅ Correcto: keys (no api_key)
keys:
  devkey: secret

rtc:
  udp_port: 7881
  tcp_port: 7882
  use_external_ip: true

room:
  auto_create: true
  max_participants: 20
  empty_timeout: 300  # ✅ Número, no string

logging:
  level: info